name: dl-challenge
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - numpy<=1.16.4
  - scipy
  - pandas
  - matplotlib
  - pytorch==1.3.*
  - cuda100
  - pip

  - scikit-image
  - scikit-learn
  - jupyterlab
  - tqdm>=4.36
  - pip:

    - onnxruntime
    - torchvision==0.4.*
